const fs = require('fs');
const path = require('path');

const mr = {
  appTitle: "स सर्व्हायवालूप",
  appTagline: "झाडांच्या जगण्यासाठी ऑपरेशनल निर्णय समर्थन आणि हस्तक्षेप व्यवस्थापन.",
  appPipeline: "संवेदना → मूल्यांकन → निर्णय → वचनबद्ध → कृती → सिद्ध करा → तपासा → अनुकूल करा",
  demoIdentity: "डेमो ओळख · सिम्युलेटेड डेटा",
  demoNotice: "डेमो सीडेड ओळख आणि स्वाक्षरी केलेले सर्व्हर-साइड सत्र वापरते. भूमिका सर्व्हरद्वारे लागू केल्या जातात, लपविलेल्या UI नियंत्रणांद्वारे कधीही नाही. सर्व प्रदर्शित डेटा सिंथेटिक आहे.",
  "role.ADMIN": "प्रशासक",
  "role.SUPERVISOR": "पर्यवेक्षक",
  "role.FIELD_WORKER": "क्षेत्र कार्यकर्ता",
  "role.AUDITOR": "लेखा परीक्षक",
  "roleBlurb.ADMIN": "पूर्ण प्रणाली नियंत्रण",
  "roleBlurb.SUPERVISOR": "पाठवणे, पुनरावलोकन, ओव्हरराइड",
  "roleBlurb.FIELD_WORKER": "माझी कार्ये आणि पुरावे",
  "roleBlurb.AUDITOR": "फक्त-वाचनीय देखरेख",
  "nav.commandCenter": "ऑपरेशन्स कमांड सेंटर",
  "nav.simulatedData": "डेमो / सिम्युलेटेड",
  "nav.liveData": "थेट डेटा",
  "nav.seed": "सीड",
  "nav.logout": "लॉग आउट",
  "kpi.active": "सक्रिय",
  "kpi.act": "कृती",
  "kpi.openTasks": "खुली कार्ये",
  "kpi.verified": "सत्यापित",
  selectCase: "प्रकरण निवडा",
  "btn.override": "ओव्हरराइड",
  "btn.act": "कृती करा",
  "btn.rerun": "⟳",
  "emptyState.select": "पुरावे, तर्क, क्षमता, एसएलए, कार्ये आणि सत्यापनाची तपासणी करण्यासाठी नकाशा किंवा रांगेतून एक घटक निवडा.",
  "footer.demo": "सर्व्हायवालूप डेमो · {dataMode} · डोमेन लॉजिक सर्व्हर-साइड आहे; UI निर्णय बदलू शकत नाही.",
  "footer.simulatedMode": "सिम्युलेटेड / सिंथेटिक डेटा — वास्तविक मोजमाप नाही",
  "footer.liveMode": "थेट डेटा",
  "queue.interventionQueue": "हस्तक्षेप रांग",
  "queue.empty": "कोणतेही कार्य नाही",
  "queue.evidence": "{count} पुरावे",
  "why.decisionRationale": "निर्णयाचे तर्क",
  "why.evidenceQuality": "पुराव्यांची गुणवत्ता",
  "why.severity": "गंभीरता",
  "why.urgency": "तातडी",
  "why.capacity": "क्षमता तपासणी",
  "why.rule": "नियम:",
  "why.overridden": "मॅन्युअल ओव्हरराइड",
  "why.sla": "एसएलए: {hours} तास",
  "evidence.title": "पुरावा संकेत लॉग",
  "evidence.empty": "अद्याप कोणतेही संकेत प्राप्त झाले नाहीत.",
  "evidence.captured": "कॅप्चर केले:",
  "task.title": "हस्तक्षेप पाठवणे",
  "task.empty": "कोणतेही पाठवणे सक्रिय नाही.",
  "task.workers": "कामगार:",
  "task.sla": "एसएलए अंतिम मुदत:",
  "verification.title": "अंमलबजावणी पुरावा",
  "verification.empty": "कोणताही अंमलबजावणी पुरावा सादर केला नाही.",
  "verification.submittedBy": "सादरकर्ते: {workers}",
  "verification.location": "स्थान: {lat}, {lng}",
  "verification.distance": "अंतर: {meters} मीटर",
  "verification.timeSkew": "वेळेतील फरक: {minutes} मिनिटे",
  "verification.notes": "टिपा:",
  "verification.photos": "फोटो संदर्भ:",
  "btn.verify": "सत्यापित करा आणि पूर्ण करा",
  "field.title": "क्षेत्र कार्ये",
  "field.availableTasks": "{count} नियुक्त कार्ये",
  "field.emptyTasks": "तुमच्याकडे कोणतेही नियुक्त हस्तक्षेप नाहीत.",
  "field.loading": "लोड होत आहे…",
  "field.taskDetails": "कार्याचे तपशील",
  "field.btnBack": "मागे",
  "field.btnAccept": "कार्य स्वीकारा",
  "field.btnStart": "हस्तक्षेप सुरू करा",
  "field.btnSubmit": "पुरावा सादर करा",
  "field.statusAssigned": "नियुक्त केले",
  "field.uploading": "पुरावे अपलोड करत आहे...",
  "field.completed": "पूर्ण झाले",
  "field.slaDeadline": "एसएलए: {date}",
  "field.coord": "कोऑर्ड: {lat}, {lng}",
  "field.evidenceCapture": "पुरावा कॅप्चर",
  "field.photoGuidance": "पूर्ण झालेल्या कामाचा फोटो घ्या",
  "field.simulatedLoc": "सिम्युलेटेड क्षेत्र स्थान",
  "field.notesPlaceholder": "अंमलबजावणी टिपा जोडा...",
  "severity.CRITICAL": "अत्यंत गंभीर",
  "severity.SEVERE": "गंभीर",
  "severity.ELEVATED": "उन्नत",
  "severity.NOMINAL": "नाममात्र",
  "decision.ACT": "कृती",
  "decision.DEFER": "पुढे ढकलणे",
  "decision.MONITOR": "निरीक्षण करणे",
  "decision.ESCALATE": "वाढवणे",
  "state.PROPOSED": "प्रस्तावित",
  "state.COMMITTED": "वचनबद्ध",
  "state.DISPATCHED": "पाठवले",
  "state.ACCEPTED": "स्वीकारले",
  "state.IN_PROGRESS": "प्रगतीपथावर",
  "state.PROOF_SUBMITTED": "पुरावा सादर केला",
  "state.COMPLETED": "पूर्ण झाले"
};

const ur = {
  appTitle: "سروائیوالوپ",
  appTagline: "درختوں کی بقا کے لیے آپریشنل فیصلہ سازی کی معاونت اور مداخلت کا انتظام۔",
  appPipeline: "احساس → تشخیص → فیصلہ → عہد → عمل → ثابت → چیک → اپنانا",
  demoIdentity: "ڈیمو شناخت · نقلی ڈیٹا",
  demoNotice: "ڈیمو بیج والی شناختوں اور دستخط شدہ سرور سائیڈ سیشن کا استعمال کرتا ہے۔ کردار سرور کے ذریعہ نافذ کیے جاتے ہیں، چھپے ہوئے UI کنٹرولز سے کبھی نہیں۔ دکھایا گیا تمام ڈیٹا مصنوعی ہے۔",
  "role.ADMIN": "ایڈمن",
  "role.SUPERVISOR": "سپروائزر",
  "role.FIELD_WORKER": "فیلڈ ورکر",
  "role.AUDITOR": "آڈیٹر",
  "roleBlurb.ADMIN": "مکمل سسٹم کنٹرول",
  "roleBlurb.SUPERVISOR": "ڈسپیچ، جائزہ، اوور رائیڈ",
  "roleBlurb.FIELD_WORKER": "میرے کام اور ثبوت",
  "roleBlurb.AUDITOR": "صرف پڑھنے کی نگرانی",
  "nav.commandCenter": "آپریشنز کمانڈ سینٹر",
  "nav.simulatedData": "ڈیمو / نقلی",
  "nav.liveData": "براہ راست ڈیٹا",
  "nav.seed": "بیج",
  "nav.logout": "لاگ آؤٹ",
  "kpi.active": "فعال",
  "kpi.act": "عمل",
  "kpi.openTasks": "کھلے کام",
  "kpi.verified": "تصدیق شدہ",
  selectCase: "کوئی کیس منتخب کریں",
  "btn.override": "اوور رائیڈ",
  "btn.act": "عمل کریں",
  "btn.rerun": "⟳",
  "emptyState.select": "ثبوت، استدلال، صلاحیت، SLA، کاموں اور تصدیق کا معائنہ کرنے کے لیے نقشے یا قطار سے کسی ہستی کا انتخاب کریں۔",
  "footer.demo": "سروائیوالوپ ڈیمو · {dataMode} · ڈومین لاجک سرور سائیڈ ہے؛ UI فیصلوں کو تبدیل نہیں کر سکتا۔",
  "footer.simulatedMode": "نقلی / مصنوعی ڈیٹا — حقیقی پیمائش نہیں",
  "footer.liveMode": "براہ راست ڈیٹا",
  "queue.interventionQueue": "مداخلت کی قطار",
  "queue.empty": "کوئی کام نہیں",
  "queue.evidence": "{count} ثبوت",
  "why.decisionRationale": "فیصلے کی دلیل",
  "why.evidenceQuality": "ثبوت کا معیار",
  "why.severity": "شدت",
  "why.urgency": "فوری پن",
  "why.capacity": "صلاحیت کی جانچ",
  "why.rule": "قاعدہ:",
  "why.overridden": "دستی اوور رائیڈ",
  "why.sla": "SLA: {hours} گھنٹے",
  "evidence.title": "ثبوت سگنل لاگ",
  "evidence.empty": "ابھی تک کوئی سگنل موصول نہیں ہوا۔",
  "evidence.captured": "کیپچر کیا گیا:",
  "task.title": "مداخلت ڈسپیچ",
  "task.empty": "کوئی ڈسپیچ فعال نہیں ہے۔",
  "task.workers": "کارکن:",
  "task.sla": "SLA آخری تاریخ:",
  "verification.title": "عمل درآمد کا ثبوت",
  "verification.empty": "عمل درآمد کا کوئی ثبوت جمع نہیں کرایا گیا۔",
  "verification.submittedBy": "جمع کرایا گیا بذریعہ: {workers}",
  "verification.location": "مقام: {lat}, {lng}",
  "verification.distance": "فاصلہ: {meters} میٹر",
  "verification.timeSkew": "وقت کا فرق: {minutes} منٹ",
  "verification.notes": "نوٹس:",
  "verification.photos": "تصویر کے حوالے:",
  "btn.verify": "تصدیق کریں اور مکمل کریں",
  "field.title": "فیلڈ آپریشنز",
  "field.availableTasks": "{count} تفویض کردہ کام",
  "field.emptyTasks": "آپ کو کوئی مداخلت تفویض نہیں کی گئی ہے۔",
  "field.loading": "لوڈ ہو رہا ہے…",
  "field.taskDetails": "کام کی تفصیلات",
  "field.btnBack": "پیچھے",
  "field.btnAccept": "کام قبول کریں",
  "field.btnStart": "مداخلت شروع کریں",
  "field.btnSubmit": "ثبوت جمع کرائیں",
  "field.statusAssigned": "تفویض کردہ",
  "field.uploading": "ثبوت اپ لوڈ ہو رہا ہے...",
  "field.completed": "مکمل",
  "field.slaDeadline": "SLA: {date}",
  "field.coord": "کوآرڈ: {lat}, {lng}",
  "field.evidenceCapture": "ثبوت کیپچر",
  "field.photoGuidance": "مکمل شدہ کام کی تصویر لیں",
  "field.simulatedLoc": "نقلی فیلڈ کا مقام",
  "field.notesPlaceholder": "عمل درآمد کے نوٹس شامل کریں...",
  "severity.CRITICAL": "انتہائی شدید",
  "severity.SEVERE": "شدید",
  "severity.ELEVATED": "بلند",
  "severity.NOMINAL": "معمولی",
  "decision.ACT": "عمل",
  "decision.DEFER": "ملتوی",
  "decision.MONITOR": "نگرانی",
  "decision.ESCALATE": "بڑھانا",
  "state.PROPOSED": "تجویز کردہ",
  "state.COMMITTED": "عہد کیا گیا",
  "state.DISPATCHED": "بھیجا گیا",
  "state.ACCEPTED": "قبول کیا گیا",
  "state.IN_PROGRESS": "جاری ہے",
  "state.PROOF_SUBMITTED": "ثبوت جمع کرایا گیا",
  "state.COMPLETED": "مکمل"
};

const placeholders = ['bn', 'ta', 'te', 'kn', 'gu', 'pa', 'ml', 'or', 'as'];
const baseDir = 'src/lib/i18n/locales';

fs.writeFileSync(path.join(baseDir, 'mr.json'), JSON.stringify(mr, null, 2));
fs.writeFileSync(path.join(baseDir, 'ur.json'), JSON.stringify(ur, null, 2));

placeholders.forEach(lang => {
  fs.writeFileSync(path.join(baseDir, lang + '.json'), '{}');
});

console.log('Dictionaries generated.');
